#include 'tlpp-core.th'
#include 'tlpp-rest.th'

//Constantes
#Define CRLF Chr(13) + Chr(10) //Carriage Return Line Feed

namespace cavanna.api.solidworks

/*------------------------------------------------------------------
Gera um novo produto no cadastro
Para¢metros via [raw body]
@author Gerson Belini
@Data 01/09/2025
------------------------------------------------------------------*/
@Post("/api/v1/solidworks/items")
user function postsolidworksitems()

    local cCodigo    := ''
    local cDescricao := ''
    local cDescespec := ''
    local cItemRevis := ''
    local nPeso      := ''
    local jBody      := ''

    jBody := JsonObject():new()
    jBody:fromJson( oRest:GetBodyRequest() )

    if ( jBody <> Nil )
        cCodigo    := jBody:GetJsonText("cod_item")
        cDescricao := jBody:GetJsonText("item_descricao")
        cDescespec := jBody:GetJsonText("item_desc_espec")
        cItemRevis := jBody:GetJsonText("item_revisao")
        
        if jBody:GetJsonText("item_peso") <> nil
            nPeso := Val(jBody:GetJsonText("item_peso"))
        endif
    endif

    processPostProducts( cCodigo , cDescricao , cDescespec, cItemRevis , nPeso )

return

/* ------------------------------------------------------------------
-------------------------------------------------------------------*/
static function processPostProducts( cCodigo , cDescricao , cDescespec, cItemRevis , nPeso )

    local cReturn := ''
    local lOK     := .T.
    local cMsg    := ''

    // Valida campo chave de busca
    if ( cCodigo == Nil .or. empty(cCodigo) )
        cCodRet := '400'
        lOK     := .F.
        cMsg    := 'invalid parameter: cod_item'
    endif

    if ( cDescricao == Nil .or. empty(cDescricao) )
        if ( !lOK )
            cCodRet := '400'
            lOK     := .F.
            cMsg    := 'invalid parameter: item_descricao'
        else
            cCodRet := '400'
            lOK     := .F.
            cMsg    += ' | invalid parameter: item_descricao'
        endif
    endif

    if ( cDescespec == Nil .or. empty(cDescespec) )
        if ( !lOK )
            cCodRet := '400'
            lOK     := .F.
            cMsg    := 'invalid parameter: item_desc_espec'
        else
            cCodigo := '400'
            lOK     := .F.
            cMsg    += ' | invalid parameter: item_desc_espec'
        endif
    endif

    if ( nPeso == Nil  )
        if ( !lOK )
            cCodRet := '400'
            lOK     := .F.
            cMsg    := 'invalid parameter: item_peso”'
        else
            cCodRet := '400'
            lOK     := .F.
            cMsg    += ' | invalid parameter: item_peso”'
        endif
    endif

    // Valida campos elegi­veis para atualizcao
    if ( lOK )
        if ( cCodigo == Nil )
            cCodigo := ''
        endif
        if ( cDescricao == Nil )
            cDescricao := ''
        endif
    endif

    if ( lOK )
        if ( !(lOK := cavprocessInsertItem( cCodigo , cDescricao , cDescespec , cItemRevis , nPeso, @cMsg  )) )
            if Empty(cMsg)
                cMsg := '.Não foi possivel inserir o produto'
            endif
        else
            cMsg := 'produto criado'
        endif
    endif

    cReturn := '{ "SUCESS": "' + if(lOK,'yes','no') + '", "MESSAGE": "' + cMsg + '" }'

    oRest:setResponse( cReturn )
return


// ------------------------------------------------------------------ //
// ------------------------------------------------------------------ //
static function cavprocessInsertItem( cCodigo , cDescricao , cDescespec , cItemRevis , nPeso , cMsg  )

    Local _aAuxCab := {}
    Local _lRet    := .F.
    Local n_X      := 1

    Private lMsErroAuto := .F.
    Private lAutoErrNoFile := .T.
    Private lMsHelpAuto :=.T.

    DbSelectArea("SB1")
    DbSetOrder(1)
    
    if !MsSeek(xFilial("SB1")+cCodigo)

        _aAuxCab := {}

        // Posicionar no complemento de produtos por grupo
        DbSelectArea("Z04")
        DbSetOrder(1)
        
        if MsSeek(xFilial("Z04")+Substr(cCodigo,1,2))

            aAdd(_aAuxCab,{"B1_FILIAL"   , xFilial("SB1")      ,NIL})
            aAdd(_aAuxCab,{"B1_COD"      , cCodigo             ,NIL})
            aAdd(_aAuxCab,{"B1_DESC"     , cDescricao          ,NIL})
            aAdd(_aAuxCab,{"B1_ESPECIF"  , cDescespec          ,NIL})

            aAdd(_aAuxCab,{"B1_TIPO"     , Z04->Z04_TIPO       ,NIL})
            aAdd(_aAuxCab,{"B1_UM"       , Z04->Z04_UM         ,NIL})
            aAdd(_aAuxCab,{"B1_LOCPAD"   , "01"                ,NIL})
            aAdd(_aAuxCab,{"B1_ZREVIT"   , cItemRevis          ,NIL})

            aAdd(_aAuxCab,{"B1_GRUPO"    , Z04->Z04_GRUPO      ,NIL})
            aAdd(_aAuxCab,{"B1_PESO"     , nPeso               ,NIL})
            aAdd(_aAuxCab,{"B1_POSIPI"   , Z04->Z04_POSIPI     ,NIL})
            aAdd(_aAuxCab,{"B1_FANTASM"  , Z04->Z04_FANTAS     ,NIL})
            aAdd(_aAuxCab,{"B1_CONTA"    , Z04->Z04_CONTA      ,NIL})
            aAdd(_aAuxCab,{"B1_CC"       , Z04->Z04_CC         ,NIL})
            aAdd(_aAuxCab,{"B1_ITEMCC"   , Z04->Z04_ITEMCO     ,NIL})
            aAdd(_aAuxCab,{"B1_PE"       , Z04->Z04_PE         ,NIL})
            aAdd(_aAuxCab,{"B1_TIPE"     , Z04->Z04_TIPE       ,NIL})
            aAdd(_aAuxCab,{"B1_FORPRZ"   , Z04->Z04_FORPRZ     ,NIL})
            aAdd(_aAuxCab,{"B1_LOCALIZ"  , Z04->Z04_LOCALI     ,NIL})

            _aAutoCab := aClone(_aAuxCab)
            

            Conout("##MsExecAuto ...  - CAVSWAPI - PROD")
            
            Begin Transaction
                MsExecAuto({|x,y| MATA010(x,y)}, _aAutoCab, 3,.T.)
                If lMsErroAuto
                    _cNomeLog := NomeAutoLog()
                    //MostraErro()
                    ConOut("Inclusao de Produtos - Erro na inclusao do item " + cCodigo + "." )
                    aLog := GetAutoGRLog()
                    varinfo("aLog", aLog)
                    cMsg := "Inclusao de Produtos - Erro na inclusao do item " + cCodigo + ":" 
                    For n_X := 21 To 22
                        cMsg += aLog[n_X] + CRLF
                    Next
                else
                    _lRet := .T.
                EndIf
            End Transaction
        else
            cMsg := "Grupo de Produto não encontrado no ERP. Revisar cadastro de grupo do ERP"
        endif
    Else
        cMsg := "Produto Já cadastrado"
    Endif

return(_lRet)

/*------------------------------------------------------------------
Gera um novo produto no cadastro
Para¢metros via [raw body]
------------------------------------------------------------------*/
@Post("/api/v1/solidworks/structures")
user function postsolidworksistructures()

    Local cproduto     := ''
    Local aComponentes := ''
    Local cComponente  := ''
    Local cSequencia   := ''
    Local nQuantidade  := 0
    Local nPerda       := 0
    Local cValid_ini   := ''
    Local cValid_fim   := ''
    Local cFantasma    := ''
    Local jBody        := ''

    jBody := JsonObject():new()
    jBody:fromJson( oRest:GetBodyRequest() )

    if ( jBody <> Nil )
        cProduto        := jBody:GetJsonText("produto")
        if jBody:HasProperty("componentes")
            aComponentes    := jbody["componentes"]
        endif

        processPoststrutctures( cProduto , aComponentes )
    endif

return

/* ------------------------------------------------------------------
-------------------------------------------------------------------*/
static function processPoststrutctures( cProduto , aComponentes )

    local cReturn := ''
    local lOK     := .T.
    local cMsg    := ''
    local nCtComp := 0

    // Valida campo chave de busca
    if ( cProduto == Nil .or. empty(cProduto) )
        cCodRet := '400'
        lOK     := .F.
        cMsg    := 'invalid parameter: produto'
    endif
    
    if ( aComponentes == Nil .or. Len(aComponentes) == 0 )
        if ( !lOK )
            cCodRet := '400'
            lOK     := .F.
            cMsg    := 'invalid parameter: componentes'
        else
            cCodRet := '400'
            lOK     := .F.
            cMsg    += ' | invalid parameter: componentes'
        endif
    endif

    // Verificar se os campos dos componentes foram enviados
    For nCtComp := 1 to Len(aComponentes)

        if ( aComponentes[nCtComp]["componente"] == nil .or. empty(aComponentes[nCtComp]["componente"]) )
            if ( !lOK )
                cCodRet := '400'
                lOK     := .F.
                cMsg    := 'invalid parameter: componente'
            else
                cCodRet := '400'
                lOK     := .F.
                cMsg    += ' | invalid parameter: componente'
            endif
        endif

        if ( aComponentes[nCtComp]["quantidade"] == nil .or. aComponentes[nCtComp]["quantidade"] == 0 )
            if ( !lOK )
                cCodRet := '400'
                lOK     := .F.
                cMsg    := 'invalid parameter: quantidade'
            else
                cCodRet := '400'
                lOK     := .F.
                cMsg    += ' | invalid parameter: quantidade'
            endif
        endif

    Next nCtComp

    if ( lOK )
        if ( !(lOK := cavprocessInsertStructure( cProduto , aComponentes, @cMsg  )) )
            cMsg += '.Não foi possivel inserir a estrutura!'
        else
            //cMsg := ' estrutura criada'
        endif
    endif

    cReturn := '{ "SUCESS": "' + if(lOK,'yes','no') + '", "MESSAGE": "' + cMsg + '" }'

    oRest:setResponse( cReturn )
return


// ------------------------------------------------------------------ //
// ------------------------------------------------------------------ //
static function cavprocessInsertStructure( cProduto , aComponentes , cMsg )

    Local _lRet    := .F.
    local nCtComp  := 0
    local nAux     := 0
    local nAcao    := 3
    Local l_Continua := .t.

    Private aAutoCab   := {}
    Private aAutoItem  := {}
    Private aAutoNew   := {}

    Private lMsHelpAuto    := .T.
    Private lAutoErrNoFile := .T.
    Private lMsErroAuto    := .F.

    dbselectarea('SB1')
    DBSETORDER(1)
    lOk := .T.
    _cCodSB1:= PADR(cProduto,TAMSX3('G1_COD')[1])
    lSB1    := IF (SB1->(MsSeek(xFilial("SB1")+_cCodSB1)),.T.,.F.)

    // Verificar se existe estrutura para o produto, não carregar novamente.
    DbSelectArea("SG1")
    DbSetOrder(1)
    
    if SB1->B1_MSBLQL != "1"
        if !SG1->(MsSeek(xFilial("SG1")+_cCodSB1))
            nAcao := 3
        else
            reclock("SB1", .f.)
            SB1->B1_REVATU := ""
            SB1->(MsUnlock())
            nAcao := 5 // iremos realizar o delete da estrutura para depois realizar a inclusao com a nova
        endif
        
        IF lSB1
            _nQtdBase := 1
            _cCodSB1  := SB1->B1_COD

            For nCtComp := 1 to Len(aComponentes)
                dbselectarea('SB1')
                DBSETORDER(1)
                _cCodSG1:= PADR(aComponentes[nCtComp]["componente"],TAMSX3('B1_COD')[1])
                lSB1    := IF (SB1->(MsSeek(xFilial("SB1")+_cCodSG1)),.T.,.F.)
                _nQuant := 0

                IF lSB1 
                    IF AllTrim(_cCodSG1) != AllTrim(_cCodSB1) .and. SB1->B1_MSBLQL != "1"

                        _cCodSG1:= SB1->B1_COD
                        _aSG1:={}
                        if aComponentes[nCtComp]["Valid_fim"] <> nil
                            dDataFim := stod(StrTran(Substr(aComponentes[nCtComp]["Valid_fim"],1,10),"-",""))
                        else
                            dDataFim := stod("20501231")
                        endif

                        AADD(_aSG1,{"G1_COD"    ,_cCodSB1        ,NIL} )
                        AADD(_aSG1,{"G1_COMP"   ,_cCodSG1        ,NIL} )
                        AADD(_aSG1,{"G1_INI"    ,DATE()          ,NIL} )
                        AADD(_aSG1,{"G1_NIV"      ,"01"            ,NIL} )
                        AADD(_aSG1,{"G1_NIVINV" ,"99"            ,NIL} )
                        AADD(_aSG1,{"G1_FIM"      ,dDataFim        ,NIL} )
                        //AADD(_aSG1,{"G1_TRT"    ,PADR('001',TAMSX3('G1_TRT')[1]),NIL} )
                        AADD(_aSG1,{"G1_QUANT"  ,aComponentes[nCtComp]["quantidade"] ,NIL} )
                        _nQuant := aComponentes[nCtComp]["quantidade"]

                        if _nQuant != 0
                            AADD(aAutoItem,aClone(_aSG1))
                            AADD(aAutoNew, aClone(_aSG1))
                        endif
                    EndIf
                Else
                    l_Continua := .f.
                    cMsg := "Componente  "+ aComponentes[nCtComp]["componente"] + " não existente no ERP! Cadastre e tente novamente!"
                endif

            Next nCtComp

            if l_Continua // nao pode ter tido erro de estrutura
                // Se for alteração adicionar os produtos que faltam na estrutura de carga e alterar a data final para a data da carga
                if nAcao == 5
                    cavVerifyStructure( cProduto , @aAutoItem )
                endif

                aAutoCab := {  {"G1_COD"   ,alltrim(_cCodSB1)  ,NIL},;
                               {"G1_QUANT"   ,_nQtdBase          ,NIL},;
                               {"NIVALT" ,"N"                ,NIL}}

                MSExecAuto({|x,y,z| pcpa200(x,y,z)},aAutoCab,aAutoItem,nAcao)
            
                if !lMsErroAuto .and. nAcao == 5 // realiza a inclusao da estrutura nova, apos o delete da antiga
                    aAutoCab := {   {"G1_COD"   ,alltrim(_cCodSB1)  ,NIL},;
                                    {"G1_QUANT" ,_nQtdBase          ,NIL},;
                                    {"NIVALT"   ,"N"                ,NIL}}

                    lMsErroAuto    := .F.
                    MSExecAuto({|x,y,z| pcpa200(x,y,z)},aAutoCab,aAutoNew,3)
                endif

                If lMsErroAuto
                    //Pegando log do ExecAuto
                    aLogAuto := GetAutoGRLog()
                    cLogTxt       := ""

                    Conout("Erro na carga da estrutura")

                    //Percorrendo o Log e incrementando o texto (para usar o CRLF você deve usar a include "Protheus.ch")
                    For nAux := 1 To Len(aLogAuto)
                        cLogTxt += aLogAuto[nAux] + CRLF
                    Next nAux
                    cMsg += cLogTxt
                Else
                    if nAcao == 5
                        cMsg := ' estrutura alterada'
                    else
                        cMsg := ' estrutura criada'
                    endif
                    _lRet := .T.
                EndIf

                lMsHelpAuto := .T.
                lMsErroAuto := .F.
                aAutoCab :={}
                aAutoItem:={}
            endif
        
        elseif SB1->B1_MSBLQL == "1"
            cMsg := "Produto bloqueado no cadastro de produto (B1_COD): "+_cCodSG1
        endif
    endif

return(_lRet)


// ------------------------------------------------------------------ //
// ------------------------------------------------------------------ //
static function cavVerifyStructure( cProduto , aAutoItem )

    Local _aAuxCab  := {}
    Local nRetAscan := 0
    Local _aSG1     := {}
    Local _lRet     := .T.

    DbSelectArea("SG1")
    DbSetOrder(1)
    SG1->(MsSeek(xFilial("SG1")+cProduto))
    
    While !SG1->(Eof()) .and. xFilial("SG1")+AllTrim(cProduto) == SG1->G1_FILIAL+allTrim(SG1->G1_COD)
        _aSG1 := {}

        if aScan(aAutoItem, {|x| AllTrim(x[2][2]) ==  AllTrim(SG1->G1_COMP)}) == 0
            AADD(_aSG1,{"G1_COD"    ,SG1->G1_COD     ,NIL} )
            AADD(_aSG1,{"G1_COMP"   ,SG1->G1_COMP    ,NIL} )
            AADD(_aSG1,{"G1_INI"    ,SG1->G1_INI     ,NIL} )
            AADD(_aSG1,{"G1_NIV"    ,SG1->G1_NIV     ,NIL} )
            AADD(_aSG1,{"G1_NIVINV" ,SG1->G1_NIVINV  ,NIL} )
            AADD(_aSG1,{"G1_FIM"    ,dDataBase       ,NIL} )
            AADD(_aSG1,{"G1_QUANT"  ,SG1->G1_QUANT   ,NIL} )
            AADD(aAutoItem,aClone(_aSG1))
        endif

        SG1->(DbSkip())
    End

return(_lRet)



/*/{Protheus.doc} Balances/Period
  Realiza a busca de um produto especifico
  @type Function
  @lucas apolinario
  @since 15/12/2025
/*/
@Get("/api/v1/solidworks/items/:cod_item")
User Function getItem()
    local cItem := ''
    local jPath := jsonObject():New()

    jPath := oRest:getPathParamsRequest()

    if (jPath <> Nil )
        cItem := jPath[ 'cod_item' ]
    endif

    cavprocessGetItem( cItem )

return 



// ------------------------------------------------------------------ //
// ------------------------------------------------------------------ //
static function cavprocessGetItem( cItem )

    local cReturn  := ''
    local lOK      := .T.
    local cMsg     := ''
    local aItem    := {}
    local aUser    := {}
    local cID      := ''
    local cDesc    := ''

    // Valida campo chave de busca
    if ( cItem == Nil .or. empty(cItem) )
        cItem := ''
        lOK   := .F.
        cMsg  := 'invalid parameter: cod_item'
    endif

    if ( lOK )
        aItem := cavgetItem( cItem )

        if ( len(aItem) == 2 )
            lOK   := .T.
            cMsg  := 'produto encontrado'
            cID   := aItem[1]
            cDesc := aItem[2]
        else
            lOK     := .F.
            cMsg    := 'produto nao foi encontrado'
        endif
    endif

    cReturn := '{ "SUCESS": "' + if(lOK,'yes','no') + '", "MESSAGE": "' + cMsg + '", "ID": "' + cID + '", "DESCRICAO": "' + cDesc + '" }'

    oRest:setResponse( cReturn )
return



// ------------------------------------------------------------------ //
// ------------------------------------------------------------------ //
static function cavGetItem( cItem )

    Local aRetItem := {}

    DbSelectArea("SB1")
    DbSetOrder(1)
    if MsSeek(xFilial("SB1")+cItem)
        aadd(aRetItem,SB1->B1_COD)
        aadd(aRetItem,SB1->B1_DESC)
    endif

return(aRetItem)
