#INCLUDE 'TLPP-CORE.TH'
#INCLUDE 'TOPCONN.CH'

#DEFINE CRLF CHR( 13 ) + CHR( 10 )

Namespace custom.CodProduct.Inteligent

/*****************************************************************************
{Protheus.doc} zCodigoInteligenteSB1GrpTipo
Função que Preenche o Código do Produto Conforme o Tipo + Grupo + Sequencial
@author João Pedro Baldasso.
@since 18/03/2026
@version 1.0
@custom.CodProduct.Inteligent.U_zCodigoInteligenteSB1GrpTipo()
*****************************************************************************/
User Function zCodigoInteligenteSB1GrpTipo()

    Local aArea    := FWGetArea()   As Array

    Local cCodigo  := ''            As Character
    Local cQryAux  := ''            As Character
    Local cGrupo   := ''            As Character
    Local cTipo    := ''            As Character
    Local cBase    := ''            As Character

    Local nTamGrp  := 0             As Numeric
    Local nTamTipo := 0             As Numeric
    Local nTamCod  := 0             As Numeric
    Local nTamSeq  := 0             As Numeric

    cTipo    := FWFldGet( 'B1_TIPO'  )
    cGrupo   := FWFldGet( 'B1_GRUPO' )
    nTamTipo := TamSX3(   'B1_TIPO'  )[ 01 ]
    nTamGrp  := TamSX3(   'B1_GRUPO' )[ 01 ]
    nTamCod  := TamSX3(   'B1_COD'   )[ 01 ]

    // Tamanho do sequencial = total - tipo - grupo
    nTamSeq := nTamCod - nTamTipo - nTamGrp

    // Só gera se ambos os campos estiverem preenchidos
    IF !Empty( cTipo ) .AND. !Empty( cGrupo )

        // Valor base = Tipo + Grupo + zeros
        cBase := cTipo + cGrupo + Replicate( '0', nTamSeq )

        // ?? Oracle ???????
        // cQryAux := " SELECT "                                                                                                               + CRLF
        // cQryAux += "     NVL( MAX( B1_COD ), '" + cBase + "' ) AS ULTIMO "                                                                  + CRLF
        // cQryAux += " FROM "                                                                                                                 + CRLF
        // cQryAux += "     " + RetSQLName( 'SB1' ) + " SB1 "                                                                                  + CRLF
        // cQryAux += " WHERE "                                                                                                                + CRLF
        // cQryAux += "     B1_FILIAL = '" + FWxFilial( 'SB1' ) + "' "                                                                         + CRLF
        // cQryAux += "     AND SUBSTR( B1_COD, 1, " + cValToChar( nTamTipo ) + " ) = '" + cTipo + "' "                                        + CRLF
        // cQryAux += "     AND SUBSTR( B1_COD,    " + cValToChar( nTamTipo + 1 ) + ", " + cValToChar( nTamGrp ) + " ) = '" + cGrupo + "' "    + CRLF

        // ?? SQL Server ???????
        cQryAux := " SELECT "                                                                                                                   + CRLF
        cQryAux += "     ISNULL( MAX( B1_COD ), '" + cBase + "' ) AS ULTIMO "                                                                   + CRLF
        cQryAux += " FROM "                                                                                                                     + CRLF
        cQryAux += "     " + RetSQLName( 'SB1' ) + " SB1 "                                                                                      + CRLF
        cQryAux += " WHERE "                                                                                                                    + CRLF
        cQryAux += "     B1_FILIAL = '" + FWxFilial( 'SB1' ) + "' "                                                                             + CRLF
        cQryAux += "     AND SUBSTRING( B1_COD, 1, " + cValToChar( nTamTipo ) + " ) = '" + cTipo + "' "                                         + CRLF
        cQryAux += "     AND SUBSTRING( B1_COD   , " + cValToChar( nTamTipo + 1 ) + ", " + cValToChar( nTamGrp ) + " ) = '" + cGrupo + "' "     + CRLF

        TCQuery cQryAux New Alias 'QRY_AUX'

        // Define o Novo Código, Incrementando 1 no Final.
        cCodigo := Soma1( QRY_AUX->ULTIMO )

        QRY_AUX->( DBCloseArea() )

    EndIF

    FWRestArea( aArea )

Return( cCodigo )
